name: "Flamed Fury: Build and Deploy"

on:
  schedule:
    - cron: 0 2/6 * * *
  push:
    branches:
      - main

jobs:
  build-main-content:
    name: "Build Main Content"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Eleventy
        uses: actions/cache@v4
        with:
          path: |
            .cache
            dist/img
          key: ${{ runner.os }}-eleventy-${{ hashFiles('src/**/*.{js,json,md}') }}
          restore-keys: |
            ${{ runner.os }}-eleventy-

      - name: Build main content
        run: |
          set -e
          npm install
          npm run build -- --ignore=index.html --ignore=feed.xml --ignore=feed.json --ignore=bookmarks-feed.json --ignore=bookmarks-feed.xml
        env:
          OMG_LOL_KEY: ${{ secrets.OMG_LOL_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          STEAM_KEY: ${{ secrets.STEAM_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TRAKT_API_KEY: ${{ secrets.TRAKT_API_KEY }}
          TRAKT_KEY: ${{ secrets.TRAKT_KEY }}
          TVDB_API_KEY: ${{ secrets.TVDB_API_KEY }}
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
          LISTENBRAINZ_USER: ${{ secrets.LISTENBRAINZ_USER }}

      - name: Deploy main content
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.CPANEL_HOST }}
          REMOTE_PORT: ${{ secrets.CPANEL_PORT }}
          REMOTE_USER: ${{ secrets.CPANEL_USER }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.CPANEL_TARGET }}
          EXCLUDE: ".git*, .github*, node_modules*, src*, index.html, feed.xml, feed.json, bookmarks-feed.json, bookmarks-feed.xml"
          ARGS: "-avzr --delete"

      - name: Cache build artifacts
        uses: actions/cache/save@v4
        with:
          path: |
            .cache/
            src/assets/fonts/
            src/assets/images/buttons
            src/assets/images/experiments
            src/assets/images/favicon
            src/assets/images/pages
            src/assets/images/posts
            src/assets/images/vinyl
            src/assets/images/template
            src/assets/og-images/
          key: 11ty-${{ runner.os }}-${{ github.run_id }}

  build-and-deploy-index-and-feeds:
    name: "Build and Deploy Index and Feeds"
    needs: build-main-content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .cache/
            src/assets/fonts/
            src/assets/images/buttons
            src/assets/images/experiments
            src/assets/images/favicon
            src/assets/images/pages
            src/assets/images/posts
            src/assets/images/vinyl
            src/assets/images/template
            src/assets/og-images/
          key: 11ty-${{ runner.os }}-${{ github.run_id }}

      - name: Build index and feeds
        run: |
          set -e
          npm install
          npm run build -- --input=. --filter=index.html --filter=feed.xml --filter=feed.json --filter=bookmarks-feed.json --filter=bookmarks-feed.xml
        env:
          OMG_LOL_KEY: ${{ secrets.OMG_LOL_KEY }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          STEAM_KEY: ${{ secrets.STEAM_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TRAKT_API_KEY: ${{ secrets.TRAKT_API_KEY }}
          TRAKT_KEY: ${{ secrets.TRAKT_KEY }}
          TVDB_API_KEY: ${{ secrets.TVDB_API_KEY }}
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
          LISTENBRAINZ_USER: ${{ secrets.LISTENBRAINZ_USER }}

      - name: Deploy index and feeds
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.CPANEL_HOST }}
          REMOTE_PORT: ${{ secrets.CPANEL_PORT }}
          REMOTE_USER: ${{ secrets.CPANEL_USER }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.CPANEL_TARGET }}
          INCLUDE: "index.html,feed.xml,feed.json,bookmarks-feed.json,bookmarks-feed.xml"
          ARGS: "-avzr"