name: "Deploy to Neocities"
on:
  schedule:
    - cron: 0 7/9 * * *
  push:
    branches:
      - main
jobs:
  deploy:
    name: "Deploy to Neocities"
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.LASTFM_KEY }}
      USERNAME: ${{ secrets.LASTFM_USER }}
      OMG_LOL_KEY: ${{ secrets.OMG_LOL_KEY }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      STEAM_KEY: ${{ secrets.STEAM_KEY }}
      STEAM_ID: ${{ secrets.STEAM_ID }}
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      TRAKT_API_KEY: ${{ secrets.TRAKT_API_KEY }}
      TRAKT_KEY: ${{ secrets.TRAKT_KEY }}
      TVDB_API_KEY: ${{ secrets.TVDB_API_KEY }}
      WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm install
      - run: npm run build
      - name: Cache dependencies and build artifacts
        uses: actions/cache@v4
        with:
          path: |
            src/assets/images/generated
            .cache
      - uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: dist